### ISSUE TITLE
Possible Enhancement

### ISSUE THREAD

**Issue by dherediat97** [sramsay64/LibreHero#1]
Hey i am programming something like LibreHero for Android(Android Native). I have the part of videos(youtube) with lyrics included (other page). I know that you want implement lyrics and video and I want implement the animation(music notes falling) of the game. 

**How can I implement with videos legally?**

I don't know download videos to mp3 legally.

👍 👍  And very good work for the App, I wanted to contact with email but dont have this in the github page.

Greetings dherediat

**Comment by sramsay64** [comment]
My plan was to get the music from peoples' itunes library. I don't know how this would work on android but for LibreHero (on a PC) I'd just scan through the `C:\Users\<user>\Music\iTunes\` folder to get music that they have (Legally) bought. Another option is to somehow integrate with Spotify. Maybe using the Java Robot class to press play on Spotify at the right time.

At the moment though I've just been using creative commons music (Brad sucks) to develop it.

I've also thought a bit about music videos because I think it would be really cool if a music video could be the background (kind of like how guitar hero has the CGI band playing on a stage. I think singstar does just this). For that I'm not to sure but I think telling the user to download the videos via keepvid and open them in LibreHero would be the best option. It would be a bit tedious so for now I'm just getting it working with music.

Also my email scottramsay64@gmail.com and I'd be happy to talk further if you want.

**Comment by dherediat97** [comment]
Hey i am implementing your proyect in Android app and the code break when create the music.

private Music makeMusic(JsonValue audioDataElem) {
		String method = audioDataElem.getString("method");
		if (method.equals("file")) {
			String file = audioDataElem.getString("file");
			return Gdx.audio.newMusic(Gdx.files.absolute(file)); // this line
		} else {
			return null;
		}
	}


Need a special permission to execute music in a smartphone?

Greetings

**Comment by sramsay64** [comment]
Are you using libGDX? I've never done any serious android development before so I don't know what the problem could be. But that code is calling libGDX libraries so you'll need that.

**Comment by dherediat97** [comment]
Solved the problem 👍
